language: c
sudo: false

compiler:
  - gcc
  - clang

script: make WITH_LUA=1 WITH_DEBUG=1 WITH_IPV6=1 WITH_WEBSOCKET=1

before_install:
  - bash .travis/setup_lua.sh
  - bash .travis/install_rocks.sh
