language: c

sudo: false

compiler:
  - gcc
  - clang

os:
  - linux
  - osx

env:
  global:
    - BUILD_TYPE=Coverage
    - ENABLE_SSL=YES
    - ENABLE_SSL_DYNAMIC_LOADING=YES
    - ENABLE_WEBSOCKETS=YES
    - ENABLE_CXX=NO
    - ENABLE_IPV6=NO
    - ENABLE_LUA=NO
    - ENABLE_LUA_SHARED=NO
    - C_STANDARD=auto
    - CXX_STANDARD=auto
  matrix:
    - BUILD_SHARED=NO
    - BUILD_SHARED=YES

addons:
  apt:
    packages:
      - cmake
    sources:
      - kubuntu-backports

before_install:
  - cmake --version

install:
  - if [ "${BUILD_TYPE}" == "Coverage" -a "${TRAVIS_OS_NAME}" == "linux" ]; then
      PATH=~/.local/bin:${PATH};
      pip install --user --upgrade pip;
      pip install --user cpp-coveralls;
    fi

before_script:
  # Generate the build scripts with CMake
  - mkdir output
  - cd output
  - cmake --version
  - cmake
    -G "Unix Makefiles"
    "-DCIVETWEB_THIRD_PARTY_DIR=${HOME}/third-party"
    -DCMAKE_BUILD_TYPE=${BUILD_TYPE}
    -DBUILD_SHARED_LIBS=${BUILD_SHARED}
    -DCIVETWEB_ENABLE_SSL=${ENABLE_SSL}
    -DCIVETWEB_ENABLE_SSL_DYNAMIC_LOADING=${ENABLE_SSL_DYNAMIC_LOADING}
    -DCIVETWEB_ENABLE_WEBSOCKETS=${ENABLE_WEBSOCKETS}
    -DCIVETWEB_ENABLE_CXX=${ENABLE_CXX}
    -DCIVETWEB_ENABLE_IPV6=${ENABLE_IPV6}
    -DCIVETWEB_ENABLE_LUA=${ENABLE_LUA}
    -DCIVETWEB_ENABLE_LUA_SHARED=${ENABLE_LUA_SHARED}
    -DCIVETWEB_C_STANDARD=${C_STANDARD}
    -DCIVETWEB_CXX_STANDARD=${CXX_STANDARD}
    ..

cache:
  directories:
  - $HOME/third-party

matrix:
  - fast_finish: true

script:
  - CTEST_OUTPUT_ON_FAILURE=1 make all test

after_success:
  - if [ "${BUILD_TYPE}" == "Coverage" -a "${TRAVIS_OS_NAME}" == "linux" ]; then
      coveralls --include src --include include --gcov-options '\-lp' --root .. --build-root .;
    fi
